// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ra2w6q3jHY1ktgn9cubOLAzA0ujTouU',
    appId: '1:463734669920:web:e97f64982bca8c39acb905',
    messagingSenderId: '463734669920',
    projectId: 'cepuapp-4aef',
    authDomain: 'cepuapp-4aef.firebaseapp.com',
    storageBucket: 'cepuapp-4aef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygazllk3OyRiONRjoN7P5uO6Qbpk_Zew',
    appId: '1:463734669920:android:142d836a2ecc011eacb905',
    messagingSenderId: '463734669920',
    projectId: 'cepuapp-4aef',
    storageBucket: 'cepuapp-4aef.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ra2w6q3jHY1ktgn9cubOLAzA0ujTouU',
    appId: '1:463734669920:web:1651cd8c0b443cf1acb905',
    messagingSenderId: '463734669920',
    projectId: 'cepuapp-4aef',
    authDomain: 'cepuapp-4aef.firebaseapp.com',
    storageBucket: 'cepuapp-4aef.firebasestorage.app',
  );
}
